# Generated by Django 5.1.5 on 2025-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='user_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
