# Generated by Django 5.1.5 on 2025-01-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0002_userlog_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
                ('license_doc', models.FileField(upload_to='contractor_licenses/')),
                ('firm_name', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('aadhaar_card', models.FileField(upload_to='contractor_aadhaar/')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.userlog')),
            ],
        ),
    ]
