# Generated by Django 5.1.5 on 2025-02-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0003_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(default='contractor', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='firm_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='license_doc',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='license_no',
        ),
        migrations.AddField(
            model_name='contractor',
            name='licenseNo',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='aadhaar_card',
            field=models.FileField(upload_to='aadhaar_cards/'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.login'),
        ),
        migrations.DeleteModel(
            name='Userlog',
        ),
    ]
