# Generated by Django 5.1.5 on 2025-02-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0004_login_remove_contractor_firm_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
