# Generated by Django 4.2 on 2025-02-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0007_migrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrant',
            name='pcc',
            field=models.FileField(default=1, upload_to='pcc/'),
            preserve_default=False,
        ),
    ]
