# Generated by Django 4.2 on 2025-02-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0008_alter_migrant_pcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='exp_date',
        ),
    ]
