# Generated by Django 4.2 on 2025-02-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0009_remove_contractor_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
