# Generated by Django 4.2 on 2025-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0010_alter_contractor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='work_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
