# Generated by Django 4.2 on 2025-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0011_contractor_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
