# Generated by Django 4.2 on 2025-02-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0012_contractor_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='state',
        ),
    ]
