# Generated by Django 4.2 on 2025-02-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0013_remove_contractor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.login'),
            preserve_default=False,
        ),
    ]
