# Generated by Django 4.2 on 2025-03-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0014_migrant_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
