# Generated by Django 4.2 on 2025-03-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0015_migrant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_description', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractor')),
            ],
        ),
    ]
