# Generated by Django 4.2 on 2025-03-18 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0016_jobbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='booked_for',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
