# Generated by Django 4.2 on 2025-03-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0017_jobbooking_booked_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='landmark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='location',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
