# Generated by Django 5.1.5 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0018_jobbooking_landmark_jobbooking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=20),
        ),
    ]
