# Generated by Django 5.1.5 on 2025-03-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0019_alter_migrant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=100)),
                ('public_phone', models.CharField(max_length=15)),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractor')),
            ],
        ),
    ]
