# Generated by Django 5.1.5 on 2025-04-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0022_policestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='police_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='migrantapp.policestations'),
            preserve_default=False,
        ),
    ]
