# Generated by Django 4.2 on 2025-02-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type_of_work',
            new_name='TypeOfWork',
        ),
    ]
