# Generated by Django 4.2 on 2025-02-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('migrantapp', '0014_migrant_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOC_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('noc', models.FileField(upload_to='NOC/')),
                ('Migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
        migrations.CreateModel(
            name='NOC_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
    ]
