# Generated by Django 4.2 on 2025-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('migrant_ids', models.TextField()),
            ],
        ),
    ]
