# Generated by Django 4.2 on 2025-03-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0015_migrant_photo'),
        ('agentapp', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='JobMigrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentapp.jobdetails')),
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
    ]
