# Generated by Django 4.2 on 2025-03-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0015_migrant_photo'),
        ('agentapp', '0003_jobdetails_jobmigrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jobdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentapp.jobdetails')),
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
        migrations.DeleteModel(
            name='JobMigrant',
        ),
    ]
