# Generated by Django 4.2 on 2025-03-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0015_migrant_photo'),
        ('agentapp', '0004_workentry_delete_jobmigrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractor')),
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
    ]
