# Generated by Django 4.2 on 2025-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0005_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
