# Generated by Django 5.1.5 on 2025-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0006_jobdetails_status'),
        ('migrantapp', '0020_jobrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='noc_table',
            constraint=models.UniqueConstraint(fields=('Migrant',), name='unique_noc_per_migrant'),
        ),
    ]
