# Generated by Django 5.1.5 on 2025-04-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0007_noc_table_unique_noc_per_migrant'),
        ('migrantapp', '0021_alter_migrant_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrantIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('migrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
    ]
