# Generated by Django 4.2 on 2025-02-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('migrantapp', '0014_migrant_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.contractor')),
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrantapp.migrant')),
            ],
        ),
    ]
