# Generated by Django 4.2 on 2025-02-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrantapp', '0014_migrant_login'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Application_request',
        ),
    ]
