# Generated by Django 4.2 on 2025-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_rename_application_application_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
