# Generated by Django 4.2 on 2025-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='firnumber',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
