# Generated by Django 4.2 on 2025-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_crimereport_firnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='resolving_note',
            field=models.TextField(null=True),
        ),
    ]
