# Generated by Django 4.2 on 2025-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_crimereport_resolving_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='resolving_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
